import { ShopProvider } from '../app/context/shopContext';
import { Cairo } from 'next/font/google';

import { ToastContainer, toast } from 'react-toastify';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './components/Header';
import axios from 'axios';
import Footer from './components/footer';



const inter = Cairo({
  subsets: ['arabic'],
  weight: ['400', '500', '700'], // الأوزان التي تريدها
  display: 'swap',
  variable: '--font-cairo',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kamsed-store",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  // const res =  await axios.get("https://store.kamsed.com/api/product/list");
   const res =  await axios.get("http://localhost:3000/api/product/list");
  const products = res.data.products || [];
  
 

  return (
    <html lang="ar"  >

      <body
        className={inter.className}
      >
        <ToastContainer/>
        <div className='xl:px-20 lg:px-10 relative sm:px-0'>
          <ShopProvider initialProducts={products}  >
            <Header  />
            {children}
           
             <Footer/>
            
          </ShopProvider>
        </div>
      </body>
    </html>
  );
}
